---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monasci-backend
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monasci-backend
  template:
    metadata:
      labels:
        app: monasci-backend
    spec:
      containers:
      - image: registry.cloud.okteto.net/monasci-assifar-karim/monasci-backend:1.0.0
        name: monasci-backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - nodePort: 30200
    port: 8080
  selector:
    app: monasci-backend
  type: NodePort