apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: monasci-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monasci-frontend
  template:
    metadata:
      labels:
        app: monasci-frontend
    spec:
      containers:
      - name: monasci-front
        image: registry.cloud.okteto.net/monasci-assifar-karim/monasci-frontend:1.0.0
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: https://backend-service-monasci-assifar-karim.cloud.okteto.net
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: monasci-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
